# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_article_url_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='issue_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_md5',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='链接的MD5'),
        ),
    ]
